Ran 4 tests in 0.005s

FAILED (failures=2, errors=1)

Error
Traceback (most recent call last):
IndexError: list index out of range


Expected 4.0, but got 5
4.0 != 5

预期:5
实际:4.0
<点击以查看差异>

Traceback (most recent call last):
AssertionError: 5 != 4.0 : Expected 4.0, but got 5


Expected 4.5, but got 6.5
4.5 != 6.5

预期:6.5
实际:4.5
<点击以查看差异>

Traceback (most recent call last):
AssertionError: 6.5 != 4.5 : Expected 4.5, but got 6.5
